### PR TITLE
add tyr tests

### PR DESCRIPTION
**Pull request by ashleygwilliams**
the tests fail, because of https://github.com/endpoints/endpoints/issues/13

but i'm p sure they are good and otherwise work. particularly because they caught this error :wink:

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
i'll squash, but i left this itemized because i wanted you to see what changes i specifically made

**Comment by bmac** [comment]
Ping @ashleygwilliams @tkellen. Whats the status of this pr? 

@fivetanley was asking me about examples of how to do acceptance tests in an endpoints app.

**Comment by tkellen** [comment]
This is going to need some major updating, it's based on pre 1.0 data.

Also, I think we need to move to representing the fixture data as JSON-API compliant objects, not the underlying database form.

**Comment by ashleygwilliams** [comment]
i agree. let's close this, come up with a new strategy, and then try again.

**Pull request closed without merging**
